### ISSUE TITLE
How should we display our score board?

### ISSUE THREAD

**Issue by magmagcup** [magmagcup/Thor#9]
How should we display our score board?
-
So we have a score board as a feature in our edu game [Trello](https://trello.com/b/5H0LhPUD/isp-thor) (in sprint 3 if you can't find it)
But I don't exactly sure how we would *Show* the score board, so I came up with 2 ideas
- The first one
> - Show scoreboard as a inividual topic
> - Use ***dropdown*** to change between each score board
> **I don't think dropdown is a best option when there are more than 10 topic , so feel free to give out your idea.**

- The second one
> -Show only 1 score board with score and topic name

**Comment by Champ2k** [comment]
I think the first way is better
